version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -q -d ${POSTGRES_DB} -h localhost -p ${POSTGRES_PORT} -U ${POSTGRES_USER}'
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      prakrikum:
  server:
    container_name: backend
    image: praktikum-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      HOST: ${HOST}
    expose:
     - "3001"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-h',
          'localost',
          '-p',
          '${POSTGRES_PORT}',
          '-U',
          '${POSTGRES_USER}'
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      prakrikum:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - '80:82'
    container_name: praktikum-server_nginx
    volumes:
      - ./fullchain.pem:/etc/cert.pem:ro
      - ./pivkey.pem:/etc/key.pem:ro
      - ./nginx:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    networks:
      prakrikum:

networks:
  prakrikum:
    name: prakrikum
